# Generated by Django 4.0.2 on 2022-11-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latlng', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
    ]
