# Generated by Django 3.2.5 on 2022-12-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221205_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.CharField(max_length=256)),
                ('janitor', models.CharField(max_length=256)),
                ('vehicle', models.CharField(max_length=256)),
                ('MCP', models.CharField(max_length=256)),
            ],
        ),
    ]
